### ISSUE TITLE
"Requested DIO channel is out of range" error

### ISSUE THREAD

**Issue by david-lemasurier** [juchong/ADIS16470-RoboRIO-Driver#8]
********** Robot program starting **********
Error at com.analog.adis16470.frc.ADIS16470_IMU.<init>(ADIS16470_IMU.java:248): Unhandled exception instantiating robot edu.wpi.first.wpilibj.SensorUtil java.lang.IndexOutOfBoundsException: Requested DIO channel is out of range. Minimum: 0, Maximum: 26, Requested: 27
        at edu.wpi.first.wpilibj.SensorUtil.checkDigitalChannel(SensorUtil.java:104)
        at edu.wpi.first.wpilibj.DigitalOutput.<init>(DigitalOutput.java:36)
        at com.analog.adis16470.frc.ADIS16470_IMU.<init>(ADIS16470_IMU.java:248)
        at com.analog.adis16470.frc.ADIS16470_IMU.<init>(ADIS16470_IMU.java:230)
        at frc.robot.Robot.<init>(Robot.java:32)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:231)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:329)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by juchong** [comment]
I remember seeing a similar issue when using older versions of the 2019 WPILib libraries. Take a look at the changelog for [this](https://github.com/wpilibsuite/allwpilib/releases/tag/v2019.4.1) WPILib release for more details. Are you sure you're using the latest 2020 libraries along with a 2020 project? If you just copied your old, 2019 project, then the project dependencies may still be pointing at older dependencies.

**Comment by ThadHouse** [comment]
Are you attempting to load in Sim? I just realized that we never upped the number of ports in simulation, so 27 is out of range in sim. I will update that in the next release of WPILib.

**Comment by david-lemasurier** [comment]
@juchong, it is a new 2020 project using the latest release of ADIS16470.
@ThadHouse, yes I am seeing this in the simulator.

**Comment by ThadHouse** [comment]
Ok. That is a wpilib bug then, it will be fixed in the next release of wpilib

**Comment by david-lemasurier** [comment]
okay, thanks.  Closing the issue.
